### ISSUE TITLE
Change namespaces and nuget names

### ISSUE THREAD

**Issue by fedj** [openzipkin/zipkin4net#117]
To be more compliant with the repository name, we need to rename the nuget and the namespaces.

Namespace: Replace Criteo.Profiling.Tracing by zipkin4net

**Comment by codefromthecrypt** [comment]
sgtm

>

**Comment by fedj** [comment]
We still need to it for middleware projects

**Comment by fedj** [comment]
Zipkin4net namespace and nuget name have been updated but not released yet.
What still needs to be done:
- [x] Remove obsolete methods/classes from zipkin4net #133 
- [x] Release zipkin4net nuget version 1.0.0
- [x] Change namespace and use new nuget in middleware.aspnetcore #136
- [x] Change namespace and use new nuget in middleware.owin #136
- [x] Remove obsolete methods/classes from middleware.aspnetcore #137
- [x] Release middleware.aspnetcore nuget version 1.0.0 #138
- [x] Release middleware.owin nuget version 1.0.0
- [x] Change namespace and use new nuget in examples/aspnet  #139 
- [x] Change namespace and use new nuget in examples/owin #140 
- [x] Add a release on github to list breaking changes
